# Generated by Django 4.1.2 on 2022-10-20 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 23, 33, 20, 670834)),
        ),
    ]
