# Generated by Django 4.1.2 on 2022-10-26 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_friendship_alter_message_message_send_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 15, 10, 56, 254451)),
        ),
    ]
