# Generated by Django 4.1.2 on 2022-10-26 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_friendship_user2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_tex',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_send_date',
        ),
        migrations.AddField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 23, 25, 23, 948255)),
        ),
    ]
